update translation for italian
OpenPrinting/cups pull request #1058
Opened 2024-09-22 09:00 UTC by luca-vercelli

Updated translations for `2.4.x`
I updated translations on https://hosted.weblate.org/projects/cups/cups/it/, then I downloaded updated .po file. I hope this is the correct workflow.
If I am not wrong, translations on Weblate are from `2.4.x`, not from `master`.

2024-09-23 10:59 UTC, zdohnal commented
Hi @luca-vercelli ,

thank you for the PR!

AFAIK translations in Weblate are for master branch (and we have to add it into master first, to prevent future regressions) - probably all the new msgids in the end of the PR are for master branch.

Would you mind removing them from this PR? Please do not squash commits, it takes lots of time to review big changes like this, so add your changes as a new commit in your PR.

2024-09-23 11:01 UTC, zdohnal requested changes
Mentioned in the comment - please remove the new English strings from the end of PR, since they look like for master branch, and we are good to go.

2024-09-23 11:01 UTC, zdohnal commented on locale/cups_it.po
> +#, c-format
The new strings from here to the end look like from master branch, please remove them since the PR is for 2.4.x branch.

2024-09-23 11:58 UTC, luca-vercelli commented
I removed strings as requested.
What should I do about master? Should I provide a new PR with the same (full) file?

2024-09-24 15:31 UTC, zdohnal commented
@luca-vercelli I will try to put your commit from 2.4.x into master - it will hopefully take less time than reviewing big MR :D .

2024-09-25 02:04 UTC, luca-vercelli commented
Probably you can just cherry-pick my *first* commit into master. Not the
second one.

Il mar 24 set 2024, 17:32 zdohnal ***@***.***> ha scritto:

> @luca-vercelli <https://github.com/luca-vercelli> I will try to put your
> commit from 2.4.x into master - it will hopefully take less time than
> reviewing big MR :D .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenPrinting/cups/pull/1058#issuecomment-2371645115>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACLII2GSSMEOHMQQYMNWUHDZYGAXZAVCNFSM6AAAAABOULZKTKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNZRGY2DKMJRGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-13 12:42 UTC, zdohnal approved these changes
LGTM!

2025-02-13 12:42 UTC, merged

2025-02-13 12:46 UTC, zdohnal commented
Thank you for the PR!