libcups: Don't overwrite permanent queue with network during discovery
OpenPrinting/cups pull request #1120
Opened 2024-12-18 08:13 UTC by zdohnal

Currently, if there is a permanent queue of the same name as network discovered printer, the network one is written in `lpstat -l -e` output. This is confusing to users and maintainers, because if print job is sent, it comes to the permanent one instead of listed network/temporary, which can have a different connection or PPD.

This behavior happens when user creates manually a queue with the same name as the temporary one, or when the permanent queue is created by cups-browsed. In both cases user realizes he prints into a different queue once he enables debugging and see printer-uri in logs.

2024-12-18 12:04 UTC, michaelrsweet requested changes
Right idea, see comments.

2024-12-19 11:56 UTC, zdohnal commented on cups/dest.c
> +    * Add destination to array if not present already...
Thx, I still put some Czechism into written English :D . fixed.

2024-12-19 11:57 UTC, zdohnal commented on cups/dest.c
> +    if (data->num_dests)
Ah, totally forget about the function, which does exactly the same I've tried to mimick... thx! Updated.

2025-04-02 15:16 UTC, michaelrsweet approved these changes

2025-04-02 15:17 UTC, merged