Parallel timeout for fetching PPD files.
OpenPrinting/cups pull request #114
Opened 2021-02-26 20:23 UTC by pranjanpr

Issue https://github.com/OpenPrinting/cups/issues/65
When some of the PPD generators took more then 60 seconds to get PPD files then `cups` expires the scheduler. 

To solve the issue, created a separate thread along with the main thread. Main thread waits for the timeout and the separate thread calls `cupsFileGets()` to get the PPD files. If it is not able to fetch it within timeout, the main thread terminates the separate thread.

@zdohnal @michaelrsweet Please review it. Thanks !

2021-02-27 20:45 UTC, michaelrsweet requested changes
This doesn't appear to do what we need it to do.

In order for this change to work, we need to run the driver interface programs in the background (in separate threads, or just poll'ing with the cupsFileNumber's which might be simpler and it will be easier to time them out together) and then limit the total amount of time they can run...

2021-02-27 20:45 UTC, michaelrsweet commented on scheduler/cups-driverd.cxx
> +#include <pthread.h>
As the pthread code in CUPS is currently *optional*, you need to make running the driver interfaces in parallel optional (and the pthread include optional) based on the HAVE_PTHREAD preprocessor define.

2021-02-27 20:45 UTC, michaelrsweet commented on scheduler/cups-driverd.cxx
> +static char             *PPDVal = NULL; /* Return value of cupsFileGets() */
Globals and threading do not go together well...

2021-02-27 20:45 UTC, michaelrsweet commented on scheduler/cups-driverd.cxx
> +  PPDVal = cupsFileGets(alias -> fp, alias -> buf, alias -> buflen);
This does not look safe or at all what I'd expect for a threaded reader...

2021-02-28 05:15 UTC, pranjanpr commented
> This doesn't appear to do what we need it to do.
> 
> In order for this change to work, we need to run the driver interface programs in the background (in separate threads, or just poll'ing with the cupsFileNumber's which might be simpler and it will be easier to time them out together) and then limit the total amount of time they can run...

Okay so the idea is to divide the ppd generators into different available threads and use `poll.h` (instead of pthread which I have done currently) in every thread such that it does not exceed timeout. I will first try to implement `poll.h` as it would be universal in every scenario such as when the CPU won't be having multiple threads.

2021-03-03 11:51 UTC, pranjanpr commented
@michaelrsweet 
SIr, I have added `poll.h` and removed the former `pthread.h` for creating timeout for PPD descriptors. Please review it. 
Thanks !

2021-03-11 11:28 UTC, michaelrsweet requested changes
No, that's not running the driver interfaces in parallel, that's just timing out a single driver interface. The goal is to run all of the driver interfaces, poll multiple file descriptors, and limit the total run time.

2023-05-31 10:40 UTC, zdohnal commented
The original issue is closed, so the enhancement is no longer required.

Thank you for the PR nevertheless!

2023-05-31 10:40 UTC, closed without merging