Only include os/availability.h if needed
OpenPrinting/cups pull request #222
Opened 2021-08-24 13:10 UTC by evanmiller

Allow building without the header (e.g. on pre-10.12 systems) via `_CUPS_SOURCE`

2021-08-24 14:13 UTC, michaelrsweet requested changes
Hmm, that'll still break if you compile something against the new headers.. Keep in mind that there is likely a LOT of stuff in current CUPS that won't compile properly on older macOS releases - it isn't like we preserved backwards build compatibility on macOS as we didn't need it...

2021-08-24 14:41 UTC, evanmiller commented
@michaelrsweet Thanks for the prompty reply. Can you please clarify your comment about compiling against the new headers? This change lets me compile with `-D_CUPS_SOURCE` and get fairly far with compilation on an old system.

Based on my reading of the header file, the availability.h macros themselves are all guarded by _CUPS_SOURCE (e.g. line 99), so guarding the header where the macros are defined seems logical.

2021-08-24 15:00 UTC, michaelrsweet commented
@evanmiller I'm just thinking of what happens once you install the software on the system - the installed headers will no longer work (no `_CUPS_SOURCE` define) so *if* we want to make CUPS 2.4.0 compile and install on older versions of macOS (problematic due to software updates and code signing) we'll want to make sure that works as well.

One of the reasons CUPS is using os/availability.h is that the old header (AvailabilityMacros.h) has been deprecated... Ideally we want something that will allow us to detect whether to use the new header...

2021-08-24 15:19 UTC, evanmiller commented
@michaelrsweet Thanks for the clarification. I had only been thinking of it as a private header, and didn't think through all the implications on the public side. If there's not an easy way to fallback to AvailabilityMacros.h, I'm happy just to maintain a private patch for now. Is `__has_include` a viable option?

For a little more context, I'm trying to bring certain CUPS components over to MacPorts so that new versions and features can be accessed on older systems. With just a handful of patches (and a few `--disable`s) I was able to build the latest libcups and ppdc on an old Tiger box – so the backward compatibility story is actually pretty good. I figured I'd send along a few of the less heinous patches here.

2021-08-31 21:38 UTC, evanmiller commented
I've updated the patch to choose between `<os/availability.h>` and `<Availability.h>` based on the outcome of `__has_include`.

2021-09-01 13:47 UTC, michaelrsweet commented
@evanmiller Hmm, that doesn't look like it will be enough, since `AvailabilityMacros.h` doesn't define the same things that `os/availability.h` does. I think you'll want to just define another `_CUPS_APPLE_OS_AVAILABILITY` macro when `os/availability.h` is present (and included), and then replace the `defined(__APPLE__)` checks with `defined(_CUPS_APPLE_OS_AVAILABILITY)`.

Again, the issue is that your fix gets CUPS to build but any non-CUPS code that tries to use the headers will break... :/

2021-09-01 14:12 UTC, evanmiller commented
What about replacing `#include <Availability.h>` with `#define API_AVAILABLE(...)` in the patch?

```
#  if defined(__APPLE__) && defined(__has_include)
#      if __has_include(<os/availability.h>)
#        include <os/availability.h>
#      else
#        define API_AVAILABLE(...)
#      endif /* __has_include(<os/availability.h>) */
#  else
#      define API_AVAILABLE(...)
#  endif /*__APPLE__ && __has_include */
```

2021-09-01 14:27 UTC, evanmiller commented
(Answering myself) I guess that still carries some problems as a public-facing header if API_AVAILABLE gets redefined etc

2021-09-01 14:53 UTC, michaelrsweet commented
@evanmiller ... but you *could* define a `_CUPS_API_AVAILABLE(...)`, e.g.:

```
#  if defined(__APPLE__) && defined(__has_include)
#      if __has_include(<os/availability.h>)
#        include <os/availability.h>
#        define _CUPS_API_AVAILABLE(...) API_AVAILABLE(__VA_ARGS__)
#      else
#        define _CUPS_API_AVAILABLE(...)
#      endif /* __has_include(<os/availability.h>) */
#  else
#      define _CUPS_API_AVAILABLE(...)
#  endif /*__APPLE__ && __has_include */
```

and then use _CUPS_API_AVAILABLE later in the file.

2021-09-08 12:47 UTC, evanmiller commented
Let me know if the latest pushes are what you had in mind.

2021-09-08 22:06 UTC, michaelrsweet commented
@evanmiller Looks good, although Codacy doesn't seem to support `__has_include` and blew up when it scanned the change, but the syntax is correct... I'll go with it and file an issue with the Codacy folks...

2021-09-08 22:06 UTC, merged