Replace %p with %s for strings in debug
OpenPrinting/cups pull request #227
Opened 2021-08-28 15:55 UTC by AtariDreams

Debugging strings makes ore sense if we get their string value instead of just their address. So most of these changes should be correct.

2021-08-28 17:23 UTC, michaelrsweet requested changes
Aside from adding the `void *` cast, I don't think we want any of these changes as-is.

2021-08-28 17:23 UTC, michaelrsweet commented on backend/ipp.c
> +          "resource=\"%s\", password_tries=%p(%d)), password=%p\n",
I'm not keen on losing the indentation to match up the starts of each piece of the format string. Either preserve the indentation or eliminate the newlines entirely (current coding style no longer requires manual wrapping at 80 columns...)

2021-08-28 17:23 UTC, michaelrsweet commented on cups/ppd-util.c
> +  DEBUG_printf(("cupsGetPPD3(http=%p, name=\"%s\", modtime=%p(%d), buffer=%s, "
This buffer may not be initialized, so it probably isn't safe to use %s here...

2021-08-28 17:23 UTC, michaelrsweet commented on cups/ppd-util.c
> +  DEBUG_printf(("4cups_get_printer_uri(http=%p, name=\"%s\", host=%s, hostsize=%d, resource=%s, resourcesize=%d, depth=%d)", http, name, host, hostsize, resource, resourcesize, depth));
Again, host isn't initialized until this function returns...

2021-08-28 17:23 UTC, michaelrsweet commented on cups/ppd.c
> +  DEBUG_printf(("2_ppdOpen: keyword=%s, string=%s", keyword, string));
The string buffer may not be initialized at this point...

2021-08-28 17:23 UTC, michaelrsweet commented on cups/sidechannel.c
> +  DEBUG_printf(("cupsSideChannelRead(command=%p, status=%p, data=%s, "
Side-channel command data is binary so we can't use %s here.

2021-08-28 17:23 UTC, michaelrsweet commented on cups/sidechannel.c
> +  DEBUG_printf(("cupsSideChannelSNMPGet(oid=\"%s\", data=%s, datalen=%p(%d), "
Ditto, binary data.

2021-08-28 17:23 UTC, michaelrsweet commented on cups/snmp.c
> +  DEBUG_printf(("4_cupsSNMPOIDToString(src=%p, dst=%s, dstsize=" CUPS_LLFMT ")",
"dst" is not yet initialized.

2021-08-28 17:23 UTC, michaelrsweet commented on scheduler/client.c
> +  cupsdLogClient(con, CUPSD_LOG_DEBUG2, "get_file: filestats=%p, filename=%s, len=" CUPS_LLFMT ", returning \"%s\".", filestats, filename, CUPS_LLCAST len, status ? "(null)" : filename);
Here we specifically report both the address *and* the value (if initialized), so no change here please.

2021-08-28 17:23 UTC, michaelrsweet commented on scheduler/process.c
> +  cupsdLogMessage(CUPSD_LOG_DEBUG2, "cupsdFinishProcess(pid=%d, name=%s, namelen=" CUPS_LLFMT ", job_id=%p(%d)) = \"%s\"", pid, name, CUPS_LLCAST namelen, job_id, job_id ? *job_id : 0, name);
Here again we show both the address and the value, so no change...

2021-08-30 14:19 UTC, AtariDreams commented
So you just want the address in debug, not the values? 

Just asking

2021-08-30 17:00 UTC, closed without merging