fix _cupsGet1284Values
OpenPrinting/cups pull request #239
Opened 2021-09-03 02:29 UTC by liuli0217

when 1284id dosen't end with semicolon，_cupsGet1284Values() cannot get last key and value.
eg.
uos@uos-PC:/usr/lib/cups/backend/snmp 10.10.120.220
network socket://10.10.120.220 "Unknown" "FUJI XEROX ApeosPort-V 4070 v  3. 43.  0 Multifunction System" "MANUFACTURER:FUJI XEROX;MODEL:ApeosPort-V 4070" ""

2021-09-05 13:00 UTC, michaelrsweet requested changes
Drop the memset and the "if (ptr > value)" and I think we'll be good. Thanks!

2021-09-06 01:08 UTC, liuli0217 commented on cups/options.c
> +    	num_values = cupsAddOption(key, value, num_values, values);
if add an empty value, and someone calls cupsGetOption() get the empty value, maybe the return value is useless for caller.

2021-09-07 16:24 UTC, michaelrsweet commented on cups/options.c
> +    	num_values = cupsAddOption(key, value, num_values, values);
Knowing that the device ID contains an empty key is useful information...

2021-09-17 14:26 UTC, michaelrsweet requested changes
@liuli0217 I just need you to resolve my last comment and then I can merge, thanks!

2021-09-18 00:23 UTC, liuli0217 commented on cups/options.c
> +    	num_values = cupsAddOption(key, value, num_values, values);
"if (ptr > value)" is removed, empty value can be added~

2021-09-26 15:03 UTC, merged