Add --enable-unlimited-idleexittime configure option
OpenPrinting/cups pull request #294
Opened 2021-11-25 08:35 UTC by zdohnal

On servers, CUPS is expected to be running permanently, even if there
are no jobs and no web interface, and CUPS doesn't share the queues.

The option will set IdleExitTimeout to 0 if used - if not used or used
with 'disable', it sets the directive to default 60s.

2021-11-25 12:51 UTC, michaelrsweet requested changes
I'm not sure why this needs to be a configure option, but I would suggest making it `--with-idle-timeout=NNN` instead of enable/disable since that is more consistent with autoconf usage and would allow a packager to configure a different timeout value as needed (vs. requiring a patch, which I suspect is what you are doing now?)

2021-11-25 15:14 UTC, zdohnal commented
@michaelrsweet 

> I'm not sure why this needs to be a configure option,

The idea is that server oriented OSes can ship preconfigured CUPS which should suit better for server use cases to prevent consuming users time and additional reports, which would end up in recommendation to set the directive.

> but I would suggest making it `--with-idle-timeout=NNN` instead of enable/disable since that is more consistent with autoconf usage and would allow a packager to configure a different timeout value as needed (vs. requiring a patch, which I suspect is what you are doing now?)

I tried to bypass value validation and reports of type 'I've set the value too low/too high and now I have problems' with choosing only unlimited option.
In this case the values are validate during reading the config, but in case of the other PR I'm planning to implement (setting systemd unit directive TimeoutStartSec for cups.service, because cups.service takes too long to start due slow disk, big data etc...) the validation on our side can happen only in .m4 file, so I've found it useful to prevent bad input at the first place.

Or we can trust in our and systemd validation code for values. WDYT?

2021-11-25 15:20 UTC, michaelrsweet commented
@zdohnal I think we can trust the input validation of cupsd and systemd to Do The Right Thing, and we can also trust that the people packaging CUPS and using this configure option have a modicum of intelligence if they decide to override the defaults. Also, `--without-idle-timeout` gives you your simple on/off option, just make sure to map a value of "no" to 0... :)

2021-11-29 08:37 UTC, zdohnal commented
@michaelrsweet ok, updated - thx for the tips, I didn't think about 'no' option at all...

2021-11-29 13:38 UTC, michaelrsweet approved these changes
LGTM

2021-11-29 13:50 UTC, merged