config-scripts: Fix --enable-libtool-unsupported
OpenPrinting/cups pull request #394
Opened 2022-05-11 19:11 UTC by orbea

Alternative fix for PR https://github.com/OpenPrinting/cups/pull/392.

Also see comment https://github.com/OpenPrinting/cups/pull/392#issuecomment-1124018535.

When the LIBTOOL variable is set in the user's environment the build will use libtool even when --enable-libtool-unsupported is not used.

This can lead to unexpected failures when LIBTOOL is set to rlibtool rather than GNU libtool.

To solve this the build now relies on the enable_libtool_unsupported varaiable set by --enable-libtool-unsupported.

Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=843638

2022-05-17 17:19 UTC, michaelrsweet commented
@orbea I am attending the PWG/OpenPrinting meeting all week, so I may not get a chance to review and test this until the end of the week...

2022-05-17 17:22 UTC, orbea commented
No worries, thank you for letting me know.

2022-07-15 15:46 UTC, michaelrsweet requested changes
OK, so this looks basically correct but why the `enable_shared=no`? The whole point of using libtool is to make it possible to create shared libraries on platforms that we don't explicitly support.

2022-07-15 16:05 UTC, orbea commented
@michaelrsweet I'm not sure why its there, but its already present in the build path with libtool disabled and I only moved the lines.

https://github.com/OpenPrinting/cups/blob/02c6a72c2fa394385b34d8c45e7a9ae2a012d17a/config-scripts/cups-libtool.m4#L17-L18

2022-07-24 16:59 UTC, michaelrsweet commented
> @michaelrsweet I'm not sure why its there, but its already present in the build path with libtool enabled and I only moved the lines.
> 
> https://github.com/OpenPrinting/cups/blob/02c6a72c2fa394385b34d8c45e7a9ae2a012d17a/config-scripts/cups-libtool.m4#L17-L18

Ah, I did some digging and the libtool support automatically creates both static and shared libraries so we disable the CUPS build system's shared library support and treat the libtool generated libraries as "static".

2022-07-24 17:52 UTC, orbea commented
Thanks for looking into that. Either way my goal with this change was to make enabling the libtool build more explicit and not cause unexpected issues with slibtool in Gentoo where I intentionally tried to not change any behavior for the libtool build in cups.

2022-07-25 12:08 UTC, merged