Correctly display "Xprinter" instead of Xerox
OpenPrinting/cups pull request #506
Opened 2022-10-25 14:53 UTC by AtariDreams

Cups currently displays "Xerox" instead of "Xprinter." This patch fixes this behavior.

2022-10-25 17:00 UTC, michaelrsweet requested changes
I think just adding a space after "XPrint" (and increasing the length by 1 in the string comparison) is enough.

2022-10-26 01:32 UTC, AtariDreams commented
Done!

2022-10-30 16:28 UTC, AtariDreams commented
@michaelrsweet Done!

2023-01-17 21:26 UTC, michaelrsweet approved these changes

2023-01-17 21:27 UTC, merged