Fix trivial deprecation
OpenPrinting/cups pull request #519
Opened 2022-11-04 15:13 UTC by AtariDreams

kIOMasterPortDefault has been renamed to kIOMainPortDefault

2022-11-09 22:28 UTC, AtariDreams commented
@michaelrsweet Ready!

2022-11-22 01:37 UTC, michaelrsweet requested changes
Non-deprecation changes are mixed with deprecation changes.

The tls-darwin.c code is EOL (the whole Security.framework was deprecated two OS releases ago).

2022-11-22 01:37 UTC, michaelrsweet commented on cups/usersys.c
> +    if ((cg->ipp_port = (int)strtol(ipp_port, NULL, 10)) <= 0)
Stick with atoi.

2022-11-22 01:37 UTC, michaelrsweet commented on cups/usersys.c
> +      cg->ipp_port = (int)strtol(port, NULL, 10);
Stick with atoi.

2022-11-22 16:42 UTC, AtariDreams commented
Fixed @michaelrsweet

2022-11-22 16:44 UTC, michaelrsweet approved these changes

2022-11-22 16:45 UTC, merged