Improve state handling in cases of memory allocation failure
OpenPrinting/cups pull request #563
Opened 2022-11-27 19:00 UTC by AtariDreams

Many lines of code assume that malloc will not fail. In cases it does, sometimes the program does not know, and as a result, memory can leak and more disasterous consequences can happen before the program ultimately finds something is wrong and then calls exit();

This PR aims to better handle memory in these cases

2022-12-01 14:50 UTC, AtariDreams commented
Also, did you know what checking for NULL before realloc is not necessary? If ptr is NULL, realloc will behave like malloc.

2022-12-01 14:59 UTC, michaelrsweet commented
@AtariDreams The `NULL` behavior with `realloc` wasn't part of C89, which is why so much of the CUPS code protects against it. Some semi-supported platforms (Solaris in particular) don't support this, so we'll be very conservative when accepting changes like this for CUPS 2.x. For CUPS 3.x we are targeting C99 and higher which cleans up a lot of legacy behaviors...

2022-12-01 16:25 UTC, AtariDreams commented
Addressed @michaelrsweet

2023-01-17 21:08 UTC, michaelrsweet requested changes
This PR seems to have a mix of changes in it and needs to be cleaned up.

2023-01-17 21:08 UTC, michaelrsweet commented on filter/rastertopwg.c
> +    if (inheader.cupsColorOrder != CUPS_ORDER_CHUNKED)
This seems unrelated to the memory allocation changes.

2023-01-17 21:08 UTC, michaelrsweet commented on scheduler/cups-driverd.cxx
> +static void		cat_ppd(const char *name, int request_id) _CUPS_NORETURN;
Unrelated.

2023-01-17 21:37 UTC, closed without merging