Remove pointless casts
OpenPrinting/cups pull request #567
Opened 2022-12-01 17:08 UTC by AtariDreams

These variables were already in the target type anyway, or implicitly converted to void *.

2022-12-01 17:54 UTC, michaelrsweet requested changes
Minor nit about strchr...

2022-12-01 17:54 UTC, michaelrsweet commented on cups/pwg-media.c
> +      (ptr = strchr(pwg, '_')) != NULL &&
Sadly, `strchr` returns `const char *` on some (C89) platforms. :/

2022-12-01 17:56 UTC, AtariDreams commented
@michaelrsweet addressed!

2022-12-02 10:34 UTC, michaelrsweet approved these changes
+1

2022-12-02 10:35 UTC, merged