Update InputSlot selection for photo sizes (fixes #569)
OpenPrinting/cups pull request #570
Opened 2022-12-02 18:04 UTC by yetamrra

_ppdCacheGetInputSlot specifically requests the photo tray for paper sizes up to 5x7" if the client hasn't specified a media-source.  This can fail if the photo tray is physically smaller than 5x7 (for example, L-sized).

Instead of explicitly requesting the photo tray, try to request "auto" and fall back to "photo" if the printer doesn't provide that as an option.

Signed-off-by: Benjamin Gordon <bmgordon@chromium.org>

2022-12-04 13:15 UTC, michaelrsweet requested changes
OK, so no need to add another global private function for this - just make the "for keyword" version a local (static) function and I'll merge.

2022-12-05 15:52 UTC, yetamrra commented
The new `_ppdCacheGetInputSlotForKeyword` function is already marked static.  Is there something more I need to do to make it a local function?

2022-12-05 16:56 UTC, yetamrra commented
Aha, gotcha.  Renamed to `ppd_inputslot_for_keyword`.  Thanks for the explanation!

2022-12-05 17:44 UTC, michaelrsweet approved these changes

2022-12-05 17:44 UTC, merged