Always release factories when done
OpenPrinting/cups pull request #655
Opened 2023-04-19 17:07 UTC by AtariDreams

There is an unlikely but still possible edge case where factories is leaked if the array being returned is not NULL but has a count of 0. This is because the CFRelease is at the end of the if statement brackets, when it should be at the end of the plugin bracket.

2023-04-22 20:12 UTC, AtariDreams commented
@zdohnal @michaelrsweet Thoughts on this?

2023-04-23 21:54 UTC, michaelrsweet commented
@AtariDreams I've been out on vacation, but regardless please don't assume we can review and respond to PRs immediately, particularly for macOS code changes that aren't being picked up by Apple... :/

2023-05-12 15:53 UTC, michaelrsweet requested changes
Some minor changes needed.

2023-05-12 15:53 UTC, michaelrsweet commented on backend/usb-darwin.c
> +  CFStringRef value;
Add comments

2023-05-12 15:53 UTC, michaelrsweet commented on backend/usb-darwin.c
> +  CFArrayRef	langArray;
Comments

2023-05-12 15:53 UTC, michaelrsweet commented on cups/tls-darwin.c
> +  if (http->tls_credentials) {
coding style

2023-05-12 16:05 UTC, AtariDreams commented
@michaelrsweet Done!

2023-05-12 18:11 UTC, michaelrsweet approved these changes

2023-05-12 18:11 UTC, merged