Use %u for unsigned, not signed
OpenPrinting/cups pull request #656
Opened 2023-04-19 18:12 UTC by AtariDreams

2023-04-23 23:13 UTC, michaelrsweet requested changes
There are some problematic changes here.

2023-04-23 23:13 UTC, michaelrsweet commented on backend/ipp.c
> +  fprintf(stderr, "DEBUG: %s IPP/%u.%u\n",
These are actually defined as signed values...

2023-04-23 23:13 UTC, michaelrsweet commented on backend/lpd.c
> +      if (lpd_command(fd, "\002%lu cfA%03d%.15s\n", (unsigned long)strlen(control),
The control file will NEVER need the range of unsigned long. Fine making this `%u` with an unsigned cast.

2023-04-23 23:13 UTC, michaelrsweet commented on backend/lpd.c
> +      fprintf(stderr, "DEBUG: Sending control file (%lu bytes)\n",
Ditto

2023-04-23 23:13 UTC, michaelrsweet commented on backend/usb-darwin.c
> +	  fprintf(stderr, "DEBUG: Wrote %u bytes of print data...\n", (unsigned)bytes);
Since "bytes" is a signed value already, no point in changing this.

2023-04-23 23:13 UTC, michaelrsweet commented on backend/usb-libusb.c
> +  unsigned char	current;			/* Current configuration */
Won't changing this to unsigned cause comparison warnings below?

2023-04-23 23:13 UTC, michaelrsweet commented on backend/usb-libusb.c
> +    fprintf(stderr, "DEBUG: Switching USB device configuration: %u -> %d\n",
Don't like a mix of signed/unsigned here...

2023-04-23 23:13 UTC, michaelrsweet commented on backend/usb-unix.c
> +  unsigned	i;				/* Looping var */
Don't mix cosmetic changes in please...

2023-05-10 14:08 UTC, AtariDreams commented
@michaelrsweet Done!

2023-05-10 18:43 UTC, michaelrsweet approved these changes
LGTM

2023-05-10 18:43 UTC, merged