Cast to unsigned-long instead of long for size_t
OpenPrinting/cups pull request #659
Opened 2023-04-20 17:32 UTC by AtariDreams

2023-04-23 23:00 UTC, michaelrsweet requested changes
Please remove unrelated changes.

2023-04-23 23:00 UTC, michaelrsweet commented on backend/snmp.c
> +	  if (!strncmp((const char *)packet.object_value.string.bytes, "lpr:", 4))
This is an unrelated change and should be removed.

2023-04-23 23:00 UTC, michaelrsweet commented on backend/snmp.c
> +	    device->uri = strdup((const char *)packet.object_value.string.bytes);
Ditto.

2023-05-01 14:48 UTC, AtariDreams commented
@michaelrsweet Addressed!

2023-05-01 18:20 UTC, michaelrsweet approved these changes

2023-05-01 18:20 UTC, merged