Always release factories when done with them
OpenPrinting/cups pull request #664
Opened 2023-04-22 18:53 UTC by AtariDreams

I am not going to sugar-coat this: there are potentially hundreds of tiny memory leaks.

The culprit is cgiGetVariable strdup the result, which allocates onto the heap, but many of these function calls assume that does not happen.

So far, I am taking the approach of freeing when done. However, given how much more messy that makes the code, I may just go along with returning a read-only pointer to the array itself, while not allowing any changes to happen.

I already made a function that checks if the result exists or is NULL without strdup, but this only checks if the variable exists.

What do you think?

2023-04-22 19:16 UTC, AtariDreams commented
@zdohnal Any advice?

2023-04-22 19:25 UTC, michaelrsweet commented
Keep in mind that the CGI programs have a very short lifetime so any “leaks” of form variables are resolved quickly when the corresponding process exits.

2023-04-22 19:44 UTC, AtariDreams commented
> Keep in mind that the CGI programs have a very short lifetime so any “leaks” of form variables are resolved quickly when the corresponding process exits.

Ok so they don't continuously run in the background like daemons tend to do, right?

2023-04-23 22:20 UTC, michaelrsweet requested changes
Remove unrelated changes.

2023-04-23 22:20 UTC, michaelrsweet commented
> Ok so they don't continuously run in the background like daemons tend to do, right?

Correct, they run and go away.

2023-05-01 19:32 UTC, michaelrsweet requested changes
Please separate changes to backend/usb-darwin.c, cups/tls-darwin.c, and ppdc/ppdc-catalog.cxx as they are unrelated to the subject issue.

Also not sure why you are adding `void *` casts to the free calls - they aren't const pointers...

Some other issues (see comments) and you really don't need to explicitly free all of the cgiGetXxx values after use. Yes, it is "cleaner" but you free something that is allocated once and then you exit, which frees all memory used by the CGI anyways. Ideally the CGI code should use the libcups string pool instead of strdup and free, but given that this code will be going away in CUPS 3.x I don't see a need to go through a lot of churn.

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/printers.c
> +    free((void *)op);
why

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/printers.c
> +    free((void *)op);
why

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/printers.c
> +  free((void *)op);
why

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/printers.c
> +      free((void *)var);
why the free and why the cast?

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/printers.c
> +      free((void *)var);
why

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/search.c
> +    free((void *)re);
why the cast?

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/search.c
> +	free((void *)s);
ditto

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/search.c
> +	  free((void *)s);
ditto

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/var.c
> +/*
two blank lines

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/var.c
> +
two blank lines

2023-05-01 19:32 UTC, michaelrsweet commented on cgi-bin/var.c
> +
two blank lines

2023-05-01 19:32 UTC, michaelrsweet commented on cups/tls-darwin.c
> +  if (credentials)
separate unrelated changes

2023-05-01 19:32 UTC, michaelrsweet commented on ppdc/ppdc-catalog.cxx
> +  if (plist) {
Separate unrelated changes.

Fix coding style/whitespace.

2023-05-02 14:23 UTC, AtariDreams commented
@michaelrsweet Done but now compilers are complaining about constness when doing free

2023-05-02 15:10 UTC, michaelrsweet commented
> @michaelrsweet Done but now compilers are complaining about constness when doing free

That's the thing, the `(void *)` casts were added to non-const pointers.

2023-05-10 14:15 UTC, closed without merging