Fix memory leaks
OpenPrinting/cups pull request #667
Opened 2023-04-23 14:27 UTC by AtariDreams

These leaks relate to CFRelease and how in some edge cases, memory may leak.

This PR fixes that.

2023-04-23 22:19 UTC, michaelrsweet requested changes
Remove unrelated changes.

Only bug fixes for macOS-specific code, and particularly the Security.framework code is deprecated and CUPS 2.4.x prefers OpenSSL/GNU TLS over the deprecated framework...

2023-04-23 22:19 UTC, michaelrsweet commented on backend/usb-darwin.c
> +  CFPlugInRef	plugin;		/* Plug-in address */
I remember this used to yield a compiler warning without the initialization.

2023-04-23 22:19 UTC, michaelrsweet commented on backend/usb-darwin.c
> +  if (result)
Unnecessary change, please limit macOS changes to bug fixes only (Apple isn't actually using OpenPrinting CUPS sources)

2023-05-02 14:26 UTC, AtariDreams commented
Merged to (https://github.com/OpenPrinting/cups/pull/655)

2023-05-02 14:27 UTC, closed without merging