thousandths should be longs
OpenPrinting/cups pull request #668
Opened 2023-04-23 16:22 UTC by AtariDreams

According to the UBSanitzer that ran during the unit tests, pwg_format_inches kept overflowing. thousandths and the other variables should be longs, not integers.

2023-04-23 16:24 UTC, AtariDreams commented
@michaelrsweet

2023-04-23 22:11 UTC, michaelrsweet requested changes
Contains unrelated change to ippeveprinter.c.

Also, the source units are hundredths of millimeters, so to overflow you'd need a media dimension over 21km, which is probably why we've never had a bug report complaining about this.

I understand the theoretical overflow, but for the normal range of values (less than 2m wide or 200000 PWG units, and less than 100m long or 10000000 PWG units) there is no overflow potential.

2023-04-23 23:25 UTC, AtariDreams commented
UBSan caught this in one of your unit tests, so something is bugged either way.

2023-04-23 23:30 UTC, AtariDreams commented
<img width="810" alt="Screen Shot 2023-04-23 at 7 29 42 PM" src="https://user-images.githubusercontent.com/83477269/233872010-154b69b3-b15d-42ae-a06e-21841c61b051.png">
@michaelrsweet The unit tests are tripping this up

2023-05-01 14:39 UTC, AtariDreams commented
@michaelrsweet @zdohnal Are the tests wrong or maybe there is a different bug that isn't the size of "thousandths"?

2023-05-06 13:23 UTC, michaelrsweet commented
Will continue to investigate...

2023-05-10 19:34 UTC, michaelrsweet commented
OK, so the calculation is for 100', which is 1200 (inches) * 2540 (hundredths of millimeters) = 3048000. Just concerned that `long` isn't guaranteed to be 64 bits...

I've pushed a different fix that eliminates the overflow:

[master 61f066e52] Fix an integer overflow issue in the PWG media size name code (Issue #668)

2023-05-10 19:34 UTC, closed without merging