UBSan: Fix operating on _fields
OpenPrinting/cups pull request #669
Opened 2023-04-23 17:15 UTC by AtariDreams

We are reading outside of the _fields boundaries and onto other fields when we iterate across all the fields, rather than comparing just those that are within _fields, and then always freeing the ones that are not.

This PR fixes that.

2023-04-23 20:16 UTC, AtariDreams commented
@michaelrsweet

2023-04-23 22:14 UTC, michaelrsweet requested changes
Please remove the unrelated ippeveprinter.c change.

The rest I need to review in more detail.

2023-04-24 04:18 UTC, AtariDreams commented
Done

2023-04-28 12:51 UTC, AtariDreams commented
@michaelrsweet Could you please look at this?

2023-04-29 17:20 UTC, AtariDreams commented
@michaelrsweet @zdohnal  Could you please look at this?

2023-05-01 11:50 UTC, michaelrsweet approved these changes
LGTM

2023-05-01 11:54 UTC, merged