UBSan: contain pos - fp->bufpos in parenthesis
OpenPrinting/cups pull request #670
Opened 2023-04-23 17:15 UTC by AtariDreams

Yes I know this shouldn't in theory change the behavior, but clang insists it does in practice, so to quiet the UBSan, I put parenthesis.

2023-04-23 22:13 UTC, michaelrsweet requested changes
Unrelated change to ippeveprinter.c needs to be removed.

Please provide the actual error message and the details of the compiler/tools that are reporting it.

2023-04-23 23:39 UTC, AtariDreams commented
<img width="810" alt="Screen Shot 2023-04-23 at 7 38 26 PM" src="https://user-images.githubusercontent.com/83477269/233872481-7d7406f5-ff7e-492d-812b-28ebcf6777d3.png">
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior http.c:315:57 in 
file.c:1828:25: runtime error: index 4372 out of bounds for type 'char[4096]

This is the clang fsanitizer

2023-04-24 12:36 UTC, AtariDreams commented
@zdohnal @michaelrsweet Simply put,

Add the parens. They are necessary. Namely, ptr + v0 - v1.
Sometimes v0 and v1 are large, but their difference is in bounds,
so you need to put parens around them, because ptr + v0 can be undefined behavior.

It's simply that the C standard declares all out-of-bounds pointers to be UB.
It doesn't matter what you do with them.

2023-04-25 20:22 UTC, AtariDreams commented
@michaelrsweet Could we please merge this one?

2023-04-25 20:49 UTC, michaelrsweet approved these changes
Complete utter bullshit, but that's the current C standard for you... Math is math...

2023-04-25 20:49 UTC, merged