Create shims to pass to array structures as to not pass incompatible function pointers
OpenPrinting/cups pull request #674
Opened 2023-04-25 14:59 UTC by AtariDreams

Although it may seem to work on modern systems, casting functions that do not have the same number of arguments as the expected type can cause ABI problems and will be removed from the latest version of C.

By sheer luck, most modern ABIs and compilers will treat the CPU register that contains the third argumentas a scratch register that may contain information from the function that called itand push it to the stack just in case. However, not all ABIs are guaranteed to do this, and because this program is not supposed to rely on these implementation details, it is best to ensure by the C standard that undefined behavior, or platform-dependent behavior, does not occur by the creation of private shim functions meant to be passed.

The reason I did this instead of changing the function definition is to maintain backwards compatibility; some of the functions being passed are public API and therefore I cannot change them.

This is the best I could do, but if there is anything else I could do, please let me know.

2023-04-25 16:17 UTC, michaelrsweet requested changes
Gave up about 3/4's through. This PR needs a LOT of work.

First, DO NOT INCLUDE UNRELATED CHANGES IN YOUR PRs.

Second, for something like this it might make sense to open an issue first, discuss your proposed changes, and then follow up. Assuming you want to continue working on these changes, you will be redoing a lot of your work to make it acceptable. In particular, I'm wondering whether it might make sense to normalize some of the string arrays with a new private API (for CUPS 2.x) like we've done for CUPS 3.x (where it is public API). Conceptually some of the new CUPS 3.x APIs will also get added to CUPS 2.5.x once we finally get 2.4.3 out and can branch.

Finally, f--k ISO for making gratuitous breaking changes to C after so many years.

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/cupsd.h
> +VAR char		*DefaultProfile	VALUE(0);
VOID NOT CHAR, don't include unrelated changes

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/cupsd.h
> +extern char		*cupsdCreateProfile(int job_id, int allow_networking);
VOID NOT CHAR, don't include unrelated changes

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/cupsd.h
> +extern int 		_cupsSafeStrcmp (const char *s1, const char *s2, void *data);
No no no. Include cups-private.h or array-private.h to get the internal definitions, don't add duplicate prototypes

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/main.c
> +    *a = cupsArrayNew3((cups_array_func_t)_cupsSafeStrcmp, NULL,
Fix naming

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/policy.c
> +static void free_policy(cupsd_policy_t *p, void *data);
Fix whitespace

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/policy.c
> +static void free_policy(cupsd_policy_t *p, void *data) /* I - Policy to free */
Fix coding style, whitespace, comments.

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/policy.c
> +hash_op(cupsd_location_t *op, void *data) /* I - Operation */
Fix coding style, whitespace, comments.

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/printers.c
> +    notifiers = cupsArrayNew((cups_array_func_t)_cupsSafeStrcmp, NULL);
Fix naming

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/process.c
> +char *					/* O - Profile or NULL on error */
VOID NOT CHAR. Do not include unrelated changes.

2023-04-25 16:17 UTC, michaelrsweet commented on scheduler/select.c
> +            void *data)       /* Unused */
Fix coding style, whitespace, comments.

2023-05-10 14:58 UTC, AtariDreams commented
@michaelrsweet Fixed!

2023-05-10 18:41 UTC, michaelrsweet requested changes

2023-05-10 18:41 UTC, michaelrsweet commented on backend/dnssd.c
> +                void *data)				/* Unused */
Fix spacing/comment:

```c
static int				/* O - Result of comparison */
compare_quirks(usb_quirk_t *a,		/* I - First quirk entry */
               usb_quirk_t *b,          /* I - Second quirk entry */
               void        *data)       /* I - Unused */
```

2023-05-10 18:41 UTC, michaelrsweet commented on backend/snmp.c
> +              void *data)					/* Unused */
Fix spacing/comment

2023-05-10 18:41 UTC, michaelrsweet commented on backend/usb-libusb.c
> +               void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cgi-bin/help-index.c
> +                  void *data)       /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cgi-bin/help-index.c
> +                   void *data)      /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cgi-bin/help-index.c
> +  (void)data;
two blank lines...

2023-05-10 18:41 UTC, michaelrsweet commented on cgi-bin/help-index.c
> +                void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/array.c
> +  if ((a = cupsArrayNew3((cups_array_func_t)_cupsArrayStrcmp, NULL, NULL, 0,
two blank lines

2023-05-10 18:41 UTC, michaelrsweet commented on cups/array.c
> +                     void *data)     /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/array.c
> +
two blank lines

2023-05-10 18:41 UTC, michaelrsweet commented on cups/array.c
> +                      void *data)          /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/array.c
> +                   void *data)    /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +static int cups_compare_dconstres(_cups_dconstres_t *a, _cups_dconstres_t *b,
fix spacing, indentation

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +static void cups_free_media_db(_cups_media_db_t *mdb, void *data);
Fix spacing/indentation

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +                       void *data)					 /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +                      void *data)					 /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +                   void *data)						/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +  dinfo->constraints = cupsArrayNew3(NULL, NULL, NULL, 0, NULL, _cupsArrayFree);
two blank lines

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest-options.c
> +								void *data)								/* I - Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/dest.c
> +    void *data)                 /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/language.c
> +                     void *data)          /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/language.c
> +                              void *data)         /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd-cache.c
> +    void *data)             /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd-cache.c
> +                  void *data)     /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd-cache.c
> +              void *data)	       /* Unused*/
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd-cache.c
> +                    void *data)             /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd-emit.c
> +                    void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd.c
> +                  void *data)     /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd.c
> +                    void *data)       /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd.c
> +                     void *data)        /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/ppd.c
> +                    void *data)       /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/pwg-media.c
> +                   void *data)			/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/pwg-media.c
> +                void *data)			/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/pwg-media.c
> +                void *data)			/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/string.c
> +                  void *data)       /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/string.c
> +                 void *data)      /* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/string.c
> +  char u, v;
Two blank lines after, add comment describing variables.

2023-05-10 18:41 UTC, michaelrsweet commented on cups/string.c
> +  char u, v;
Ditto

2023-05-10 18:41 UTC, michaelrsweet commented on tools/ippfind.c
> +                 void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on tools/ippeveprinter.c
> +             void *data)			/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/type.c
> +                   void *data)			/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/subscriptions.c
> +									 void *data)						/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/subscriptions.c
> +    void *unused)	/* I - Unused user data pointer */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/select.c
> +            void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/quotas.c
> +               void *data)							/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/process.c
> +              void *data)					/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/printers.c
> +								 void *data)		/* I - App data (not used) */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/policy.c
> +        void *data)						/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/policy.c
> +                        void *data)						/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/policy.c
> +                 void *data)				/* Unused */
Fix spacing/comment.

2023-05-10 18:41 UTC, michaelrsweet commented on scheduler/policy.c
> +            void *data)						/* Unused */
Fix spacing/comment.

2023-05-11 17:25 UTC, AtariDreams commented
@michaelrsweet Done!

2024-04-02 22:27 UTC, michaelrsweet approved these changes
I'll do the cleanup noted in the comments...

2024-04-02 22:27 UTC, michaelrsweet commented on cups/array.c
> +                         (cups_acopy_func_t)_cupsStrPrivAlloc,
Let's use your `_cupsArrayStrdup` and `_cupsArrayFree` here, no need to use the string pool functions...

2024-04-02 22:27 UTC, michaelrsweet commented on cups/string-private.h
> +extern char *_cupsStrPrivAlloc(const char *s, void *data) _CUPS_PRIVATE;
Drop these...

2024-04-02 22:27 UTC, michaelrsweet commented on cups/string.c
> + * '_cupsStrPrivAlloc()' - Allocate/reference a string.
Drop these...

2024-04-02 22:45 UTC, michaelrsweet approved these changes

2024-04-02 22:45 UTC, merged