lpstat, cupsd: Introduce the value `successful` for 'which' attr
OpenPrinting/cups pull request #830
Opened 2023-11-21 18:05 UTC by zdohnal

`lpstat` does not have a way how to show successful jobs. One possible solution would be to rewrite the behavior of 'completed' type, but this can cause discrepancies in behavior which some users can expect.

Fixes #828

2023-11-21 18:14 UTC, michaelrsweet commented
If you want to extend "which-jobs" values, you need to propose this on the IPP workgroup mailing list in the Printer Working Group...

2023-11-23 14:36 UTC, zdohnal commented
Found out a bug in setting job->state_reasons - they are always 'proccessing-to-stop-point', because we always call cupsdSetJobState() from finalize_job() with forcing the status update. I'll send patch as well.

2023-11-23 15:29 UTC, michaelrsweet requested changes
Won't you need to also change the code that adds the "which-jobs" attribute in the Get-Jobs request?

2023-11-23 15:48 UTC, zdohnal commented
@michaelrsweet I've changed it - there is ternary operator when I construct the request and putting which-jobs in.

2023-11-23 16:39 UTC, michaelrsweet approved these changes

2023-11-23 16:39 UTC, michaelrsweet commented on systemv/lpstat.c
> +	if (!strcmp(which, "successful") && (!reasons || (reasons &&
This could also be looking at the job-state value (`IPP_JSTATE_COMPLETED`).

2023-11-24 06:26 UTC, merged