Debian: Run testlang for each CUPS locale
OpenPrinting/cups pull request #85
Opened 2021-02-03 18:00 UTC by OdyX

… and only for these.

Of the build environment forces LC_ALL to a non-provided locale, the build will fail.

For instance, the Debian reproducible builds' initiative runs builds under arbitrary locales; specifically the `testlang` make target will fail when run with `LC_ALL=kz_KZ` for example.

2021-02-03 19:10 UTC, michaelrsweet requested changes
The only problem with this change is that on macOS the locale testing loops through the system-defined locales. It would be better for testlang to loop through the locales it finds in the locale directory on platforms other than macOS.

2021-02-03 19:55 UTC, OdyX commented
Hrm. That's what this does; isn't it?

https://github.com/OpenPrinting/cups/pull/85/files#diff-1efbe8fd9c6e7d6e5860183a59c31b47bb08f92e6fc3c2da273c90d9ba4570f1L638

2021-02-03 20:09 UTC, michaelrsweet commented
@OdyX 

> Hrm. That's what this does; isn't it?
> 
> https://github.com/OpenPrinting/cups/pull/85/files#diff-1efbe8fd9c6e7d6e5860183a59c31b47bb08f92e6fc3c2da273c90d9ba4570f1L638

No, your change removes the testing of macOS locales and scripts the testing of configured languages.

What I want to see is the loop over configured languages to be put in the testlang program itself, so that on macOS we can continue to test all system locales (which have been a historical source of problems) and on Linux/others we can test all configured locales.

The macOS code starts on line 185 of testlang.c, we just need to adapt it to test all the locales in the "locale" directory.

2021-02-12 13:19 UTC, OdyX commented
OK. On second reading, I got what you meant. Unfortunately, I don't have a MacOS at hand to implement this.

2021-02-12 16:08 UTC, michaelrsweet commented
@OdyX Nothing to implement, just do your test with an `#else` after the `#ifdef __APPLE__` that loops through the Apple language identifiers.

2021-03-01 12:29 UTC, michaelrsweet commented
[master 74418acb4] Update testlang to test all locales (Issue #85)

2021-03-01 12:29 UTC, closed without merging