ppd-emit.c: Fix SEGV in 'ppdEmitString()'
OpenPrinting/cups pull request #850
Opened 2023-12-27 13:35 UTC by Drawishe

When using `testppd.c` as a harness, a fuzzer found a way to call `ppdPageSize()` with NULL return value.
This caused a segmentation fault because the size structure, which is used by `values[pos]`, was assigned a NULL value.
To avoid this, we need to add a NULL value check for the size structure, free allocated memory, and return NULL.

Fixes #849

2024-01-02 12:21 UTC, zdohnal requested changes

2024-01-02 12:21 UTC, zdohnal commented on cups/ppd-emit.c
> +          return(NULL);
Looks good in general, only a code style issue - please put a space between return and (NULL);.

2024-01-02 12:22 UTC, zdohnal commented
Note to myself - push it into libppd once merged.

2024-01-03 13:16 UTC, zdohnal approved these changes
LGTM, thank you Kirill!

2024-01-04 09:53 UTC, merged

2024-01-04 09:53 UTC, zdohnal commented
@Drawishe thank you for the fix!

2024-01-04 11:53 UTC, zdohnal commented
One late note - it would be great if you stashed the commits next time if possible, it gives cleaner git history.

2024-01-04 13:17 UTC, jsmeix commented
@zdohnal 
did you really mean "git stash"?

2024-01-04 15:49 UTC, zdohnal commented
@jsmeix thanks Johannes, it was really "squash"....