Update Russian translation
OpenPrinting/cups pull request #852
Opened 2023-12-29 17:34 UTC by OlesyaGerasimenko

2023-12-30 14:16 UTC, michaelrsweet requested changes
Huh, still doesn't have the filtering code in it... :/ Are you sure you've updated your fork with the latest changes from OpenPrinting:master?

2023-12-30 19:34 UTC, OlesyaGerasimenko commented
Weird, the code seems to be in place: https://github.com/OpenPrinting/cups/pull/852/commits/1f71a7a34973e2bcafbba70bf93e87d150398cf8

2024-01-02 12:09 UTC, zdohnal commented
Hi @OlesyaGerasimenko ,

I'm not a Git expert, but I can tell you what works for me when I want to create a pull request:

- clone the upstream (OpenPrinting CUPS) repo on Github,
- in terminal, clone personal OpenPrinting CUPS clone to local machine with f.e. ```git clone git@github.com:zdohnal/cups.git```
- add OpenPrinting CUPS as another remote with ```git remote add upstream https://github.com/OpenPrinting/cups```

This gives me basic setup - I can push into my repo by default and I can always fetch upstream changes from OpenPrinting by ```git pull --rebase upstream master``` and push them to my clone by ```git push```.

Then I create a separate branch by ```git checkout -b <branch-name>``` and push my changes into it - pushing the changes into master may work for one time contribution (if I delete the Github repo once it is merged) if I am lucky - otherwise it can get difficult if there are conflicts and the git history becomes less readable (at least in my case - I always want my local master to be 1-to-1 with upstream master branch, since it shows me what is in upstream more clearly). Once I have committed all changes, I push a new branch by ```git push --set-upstream origin <branch-name>```.

And if there are new changes in upstream master, I have to propagate them into my branch:

- first I take changes from upstream repo - ```git pull --rebase upstream master && git push``` when I am in local master branch of my clone,
- switch to my branch by ```git checkout <branch>```,
- rebase the branch according master branch by ```git rebase -i master```,
- solve any possible conflicts - in case my changes should rewrite upstream changes, remove blocks from upstream (any conflicting line blocks are marked by >>>> and <<<< - those have to be solved) and vice versa. If upstream changes are not related to my changes, I have to adjust the code to contain both (this is what happened to you - upstream changes are not related to your changes, so you had to keep them, but they were removed instead, which is an issue),
- once rebase finishes (there are clear instructions on command line how to proceed during rebase) push the changes with ```git push --force```.

If I check your git history, I see you have tried to merge master branch of OpenPrinting CUPS, but it does not look like recent HEAD of master branch.

If I were you, I would take my changes and delete my cloned github repo, since it would be easiest for me, but in case you would like to keep your repo:

- you can cherry pick your changes by ```git format-patch -1 <commit ID>,
- do hard reset to the commit before you made changes by ```git reset --hard origin <commit ID before you started to make changes> && git push --force```,
- check if you have the remote set by ```git remote -v``` - if not, add it via ```git remote add``` command above,
- update your repo by ```git pull --rebase upstream master && git push```,
- apply your changes and fix any possible conflicts (beware of removing any changes which come from upstream :)),
- Github should now see your changes.

2024-01-09 03:11 UTC, ValdikSS requested changes

2024-01-09 03:11 UTC, ValdikSS commented on templates/ru/printer.tmpl
> +{server_is_sharing_printers=0?не:{printer_is_shared=0?не:}} использует совместный доступ{default_name={printer_name}?, установлен по умолчанию:})</H2>
Принтер может быть без возможности совместного (общего) доступа (не расшарен по сети для других пользователей), а может быть с совместным доступом (расшарен по сети).

Использует совместный доступ — неверно.

Сам оборот "совместный доступ" не очень звучит, если придумаете, как перефразировать более удачно — дерзайте.

2024-01-09 03:11 UTC, ValdikSS commented on templates/ru/printer.tmpl
> +{printer_commands~.*PrintSelfTestPage.*?<OPTION VALUE="print-self-test-page">Печать страницы самопроверки</OPTION>:}
Doesn't sound right, Windows also uses пробная страница.

2024-01-09 03:11 UTC, ValdikSS commented on templates/ru/printer.tmpl
> +{printer_state=5?<OPTION VALUE="start-printer">Продолжить печать</OPTION>:<OPTION VALUE="stop-printer">Приостановить печать</OPTION>}
"Продолжить" звучит непонятно, хоть и более грамотно.
Предлагаю оставить восстановление — и, возможно, заменить "приостановку" на "удержание", раз вы выше сделали с заданиями такое.

Или просто оставить как есть.

2024-01-09 03:11 UTC, ValdikSS commented on templates/ru/printers.tmpl
> +<TR><TH>Имя очереди</TH><TH>Описание</TH><TH>Расположение</TH><TH>Марка и модель</TH><TH>Статус</TH></TR>
Производитель, не марка

2024-02-16 21:06 UTC, ValdikSS commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
@michaelrsweet could you clarify why `Withheld` is used in English here, in `job_originating_user_name`? It always print `Withheld` for me when I use driverless printing.

2024-02-16 21:27 UTC, michaelrsweet commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
"Withheld" is shown when you don't have authentication enabled, so for privacy reasons we don't provide personally identifying information...

2024-02-16 21:49 UTC, ValdikSS commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
@michaelrsweet also in .po file, should we translate WARN and FAIL, are these loglevels or just the text?

2024-02-16 21:52 UTC, ValdikSS commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
> "Withheld" is shown when you don't have authentication enabled, so for privacy reasons we don't provide personally identifying information...

Oh, so it's `unknown` then, gotcha.

2024-02-16 23:56 UTC, michaelrsweet commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
> @michaelrsweet also in .po file, should we translate WARN and FAIL, are these loglevels or just the text?

The WARN, ERROR, PASS, and FAIL prefixes should not be localized.

2024-02-17 06:31 UTC, ValdikSS commented on templates/ru/jobs.tmpl
> +<TD>{?job_originating_user_name=?Приостановка:{job_originating_user_name}}&nbsp;</TD>
> The WARN, ERROR, PASS, and FAIL prefixes should not be localized.

Just FIY they are localized in ca, es, ja, pt_BR, zn_CN.

2024-04-06 13:38 UTC, closed without merging

2024-04-06 13:38 UTC, michaelrsweet commented
Closing this for now, please open a fresh PR once you have resolved the issues.

2024-04-06 14:12 UTC, ValdikSS commented
@michaelrsweet, #895 and #894 are updated versions of this translation.