Update man pages for default printer
OpenPrinting/cups pull request #865
Opened 2024-01-15 15:28 UTC by zdohnal

Attempt to make explanation where the default printer is taken from clearer:

$HOME/lpoptions (/etc/cups/lpoptions for root) > ENV variables LPDEST/PRINTER > Server Default

Fixes #819

2024-01-15 16:06 UTC, michaelrsweet requested changes
Some minor issues here. Also possible issue with the lpstat -W text (missing quotes around "all"...)

2024-01-15 16:15 UTC, zdohnal commented on man/lpoptions.1
> +.B LPDEST
@michaelrsweet don't you mean the line above? The page looks IMO better that way (after several years of programming, I found out ```man``` can open files as well! :D )

```
.SH ENVIRONMENT VARIABLES
.TP 5
.B LPDEST
```

2024-01-15 16:25 UTC, michaelrsweet commented on man/lpoptions.1
> +.B LPDEST
Yes, as you've shown (SH, TP, B). Otherwise the indentation is messed up.

2024-01-15 16:29 UTC, zdohnal commented on doc/help/man-lpstat.html
> +Specifies which jobs to show, &quot;all, &quot;successful&quot;, &quot;completed&quot; or &quot;not-completed&quot; (the default).
It was already in master, but mantohtml was not used regenerate html - I'll fix it too.

2024-01-15 16:33 UTC, zdohnal commented
Hopefully fixed by the latest commit - feel free to check.

2024-04-06 13:32 UTC, michaelrsweet commented
I believe we've picked up all of these changes, closing. If there is something I've missed please create a fresh PR or just commit the necessary changes directly. :)

2024-04-06 13:32 UTC, closed without merging