cups/string.c: Add `_cups_snprintf()`
OpenPrinting/cups pull request #867
Opened 2024-01-16 15:48 UTC by zdohnal

Add the function which will remove the truncated UTF-8 multibyte characters.

2024-01-16 15:54 UTC, michaelrsweet requested changes
I was actually thinking of adding a public API - `cupsFormatString` - and also want to do some other filtering of invalid/unsafe chars like we do for logging.

2024-01-17 12:50 UTC, michaelrsweet commented
> @michaelrsweet ok, I made the function public + used _cups_safe_vsnprintf(), which does the job for logging - however it seems there was a bug in the function, which returned shorter string than the maximum possible, and returned higher number of written bytes than it actually wrote.

Actually, that is the correct behavior. `(v)snprintf` return the number of bytes that would have been written, not the number of bytes written.

2024-01-17 12:57 UTC, michaelrsweet requested changes
See comments...

2024-01-17 16:35 UTC, zdohnal commented on cups/debug.c
> +            for (; *s && bufptr < bufend; s ++)
The decrement is there to prevent buffer overflow if we add an escaping character, right?

Shouldn't we check it in the specific 'ifs'? Otherwise this way we will lose one more character from string to additional null?

2024-01-25 02:24 UTC, michaelrsweet commented on cups/debug.c
> +            for (; *s && bufptr < bufend; s ++)
Thanks, yes but I ended up doing things a little differently and pushed the results to CUPS 2.5 and libcups v3.

2024-01-25 02:25 UTC, michaelrsweet commented
Fixes are in master.

2024-01-25 02:25 UTC, closed without merging

2024-01-25 11:55 UTC, michaelrsweet commented
@zdohnal For sure, aside from fixing the bug in this function, it also lead to related fixes in the `cupsCopy/ConcatString`. And we also promoted the old `_cups_safe_snprintf` function to API.