Fixes web UI  for non-existing printer/class
OpenPrinting/cups pull request #876
Opened 2024-01-26 19:48 UTC by TheJayas

Fixes Issue #423 : 
When user open the api for any unknown classes or printers, then previously it was showing a random UI with that printer/class name.
Now it will throw "404:NOT FOUND" error for those cases.
Example for : http://localhost:631/classes/testclass or http://localhost:631/printers/testpriner

2024-01-26 19:51 UTC, TheJayas commented
@tillkamppeter , Please check this pull request and suggest if some changes are required.

2024-01-26 21:01 UTC, michaelrsweet requested changes
So if there are no printers or classes then we should show "no printers" or "no classes", not return a cryptic "404:NOT FOUND" message.

2024-01-27 04:36 UTC, TheJayas commented
Please review the new changes

2024-01-27 19:22 UTC, michaelrsweet requested changes
OK, no.

The place to change this is in the HTML templates (printers.tmpl and classes.tmpl) to change the current empty content to something like "No printers added.". You don't need to change the CGI programs for that.

2024-01-28 16:57 UTC, TheJayas commented
Required changes are made. @michaelrsweet please review it.

2024-01-29 12:11 UTC, michaelrsweet requested changes
That's not what I was suggesting for a change...

> What are you trying to accomplish with this change?

2024-01-29 13:21 UTC, TheJayas commented
I have changed the templates file of classes and printers such that whenever someone directly enter web address like  : http://localhost:631/classes/testclass
then if there is no class with name "testclass", then that web address will render "ERROR: NO CLASS FOUND".
Similiar will happens in case of printers.
Previously the above web address was rendering unavailable class with name "testclass" which do not even exists.

2024-02-01 13:55 UTC, TheJayas commented
@michaelrsweet  please review the changes.

2024-02-10 07:02 UTC, TheJayas commented
@tillkamppeter , please review the changes, this time I have undo all the changes that were made in .c files and I have changes two templates , "class.tmpl" and "printer.tmpl" to solve the issue.

2024-02-10 22:30 UTC, tillkamppeter commented on cgi-bin/classes.c
> -
Why are you removing these comments?

2024-02-10 22:30 UTC, tillkamppeter commented on cgi-bin/printers.c
> -
Why are you removing these comments?

2024-02-10 22:31 UTC, tillkamppeter commented on .vscode/settings.json
> +}
Why are you adding this file?

2024-02-10 22:53 UTC, TheJayas commented
Oh sorry, I think comments are removed by mistake, and that file might be created due to my code editor's fault., these things do not have to do anything with solving issue.

2024-03-17 08:33 UTC, closed without merging