Fixed a couple of gcc warnings
OpenPrinting/cups pull request #887
Opened 2024-02-08 09:00 UTC by alexpevzner

In cups/dest.c:

    dest.c:1830:21: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
     1733 |       DEBUG_printf(("1cupsGetNamedDest: Using name=\"%s\"...", name));
	  |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is really true, and gcc was smart enough to deduct it from context. Obviously, we meant to print dest_name here.

In cgi-bin/search.c:

    search.c:191:29: warning: pointer ‘s’ may be used after ‘realloc’ [-Wuse-after-free]
      191 |         sptr = temp + (sptr - s);
	  |                       ~~~~~~^~~~

The code is correct, but too hard for gcc to analyze. So code simplified a bit to make compiler happy.

2024-02-08 12:33 UTC, michaelrsweet requested changes
Please omit the `(sptr - s)` change and update the debug printf.

2024-02-08 12:33 UTC, michaelrsweet commented on cgi-bin/search.c
> +        char	*temp;			/* Temporary string pointer */
Don't bother working around compiler bugs...

2024-02-08 12:33 UTC, michaelrsweet commented on cups/dest.c
> +      DEBUG_printf("1cupsGetNamedDest: Using name=\"%s\"...", dest_name);
Might as well change the debug printf to say `dest_name=\"%s\"`

2024-02-08 16:06 UTC, alexpevzner commented
Done

2024-02-08 16:34 UTC, tillkamppeter approved these changes

2024-02-09 00:11 UTC, michaelrsweet approved these changes
+1

2024-02-09 04:31 UTC, merged